const data = [
  {
    id: 2138,
    title: "React Projects",
    projects: [
      {
        id: 1,
        name: "Birthday Reminder",
        photo: "./images/birthday.png",
        link: "https://birthday-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 2,
        name: "Tours",
        photo: "./images/tour.png",
        link: "https://tour-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 3,
        name: "Reviews",
        photo: "./images/reviews.png",
        link: "https://reviews-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 4,
        name: "Accordion",
        photo: "./images/accordion.png",
        link: "https://accordion-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 5,
        name: "Menu",
        photo: "./images/menu.png",
        link: "https://menu-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 6,
        name: "Tabs",
        photo: "./images/tabs.png",
        link: "https://tabs-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 7,
        name: "Slider",
        photo: "./images/slider.png",
        link: "https://slider-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 8,
        name: "Dummy Text Generator",
        photo: "./images/lorem.png",
        link: "https://dummytext-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 9,
        name: "Color Generator",
        photo: "./images/color.png",
        link: "https://color-generate-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 10,
        name: "Todo List",
        photo: "./images/grocery.png",
        link: "https://todo-react-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 12,
        name: "Sidebar and Modal",
        photo: "./images/sidebar.png",
        link: "https://sidebar-modal-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 13,
        name: "Stripe Menu",
        photo: "./images/stripe.png",
        link: "https://stripe-layout-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 14,
        name: "Cart",
        photo: "./images/cart.png",
        link: "https://cart-item-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
        id: 15,
        name: "Cocktails",
        photo: "./images/cocktail.png",
        link: "https://cocktail-proj.netlify.app",
        description: "",
        category: "basic",
      },
      {
          id:16,
          name:"Chat Project With Firebase",
          photo:"./images/fb_chat.png",
          link:"https://fb-chat-proj.netlify.app/",
          description:"",
          category:"advanced"
      },
      {
        id: 17,
        name: "Markdown Preview",
        photo: "./images/markdown.png",
        link: "https://markdown-react-project.netlify.app/",
        description: "",
        category: "advanced",
      },
      // {
      //   id: 18,
      //   name: "Random Person",
      //   photo: "./images/random.png",
      //   link: "#",
      //   description: "",
      //   category: "advanced",
      // },
      {
        id: 19,
        name: "Disney Home Clone",
        photo: "./images/disney.png",
        link: "https://disney-home-clone.netlify.app/",
        description: "",
        category: "advanced",
      },
        {
        id: 20,
        name: "Netflix Clone",
        photo: "./images/netflix.png",
        link: "https://netflix-sg.netlify.app/",
        description: "",
        category: "advanced",
      },
      // {
      //   id: 20,
      //   name: "Stock Photos",
      //   photo: "./images/stock.png",
      //   link: "#",
      //   description: "",
      //   category: "advanced",
      // },
      // {
      //   id: 21,
      //   name: "Dark Mode",
      //   photo: "./images/dark.png",
      //   link: "#",
      //   description: "",
      //   category: "advanced",
      // },
      // {
      //   id: 22,
      //   name: "Movies DB",
      //   photo: "./images/movies.png",
      //   link: "#",
      //   description: "",
      //   category: "advanced",
      // },
      // {
      //   id: 23,
      //   name: "Hacker News",
      //   photo: "./images/hacker.png",
      //   link: "#",
      //   description: "",
      //   category: "advanced",
      // },
      // {
      //   id: 24,
      //   name: "Quiz",
      //   photo: "./images/quiz.png",
      //   link: "#",
      //   description: "",
      //   category: "advanced",
      // },
      {
        id: 25,
        name: "Github Users",
        photo: "./images/github.png",
        link: "https://github-search-proj.netlify.app/",
        description: "",
        category: "large-scale",
      },
      {
        id: 26,
        name: "E-Commerce",
        photo: "./images/ecommerce.png",
        link: "https://techdeal-dj-react.herokuapp.com/",
        description: "",
        category: "large-scale",
      },
    ],
  },
  { title: "Django Projects" ,
  projects:[
      {
        id: 27,
        name: "Eshikshapie (Production)",
        photo: "./images/eshikshapie.png",
        link: "https://www.eshikshapie.com",
        description: "",
        category: "large-scale",
      },

      {
        id: 29,
        name: "PMS",
        photo: "./images/pms.png",
        link: "https://pms-dj.herokuapp.com/",
        description: "",
        category: "large-scale",
      },
  ]

},
  { title: "Django React Projects" ,
  projects:[
     
      {
        id: 28,
        name: "TechDeal",
        photo: "./images/techdeal.png",
        link: "https://techdeal-dj-react.herokuapp.com/",
        description: "",
        category: "large-scale",
      },
    
  ]

},
];

export default data;
